#!/usr/bin/env python3
"""
Ralph Wiggum Stop Hook - "I'm helping!"

This hook intercepts Claude Code's exit and re-injects work if tasks remain incomplete.
Named after Ralph Wiggum's enthusiastic "I'm helping!" attitude.

How it works:
1. Checks for unprocessed files in AI_Employee_Vault/Needs_Action/
2. Tracks iteration count to prevent infinite loops
3. If work remains and under max iterations: continues working
4. If done or max iterations reached: allows Claude to stop

Exit codes:
- 0: Continue (hook injected new work)
- 0: Stop (no work remaining or max iterations reached)
"""

import os
import sys
from pathlib import Path
from datetime import datetime
import json

# Configuration
MAX_ITERATIONS = int(os.environ.get('RALPH_MAX_ITERATIONS', '10'))
NEEDS_ACTION_DIR = Path('AI_Employee_Vault/Needs_Action')
IN_PROGRESS_DIR = Path('AI_Employee_Vault/In_Progress')
PLANS_DIR = Path('AI_Employee_Vault/Plans')
LOOP_STATUS_FILE = PLANS_DIR / 'loop_status.md'

def log(message):
    """Log to stderr so it doesn't interfere with hook output"""
    print(f"[Ralph Hook] {message}", file=sys.stderr)

def get_unprocessed_files():
    """Get list of unprocessed files in Needs_Action"""
    if not NEEDS_ACTION_DIR.exists():
        return []

    unprocessed = []

    for file_path in NEEDS_ACTION_DIR.glob('*.md'):
        # Skip files starting with underscore (temp/system files)
        if file_path.name.startswith('_'):
            continue

        # Skip if already in In_Progress
        in_progress_path = IN_PROGRESS_DIR / file_path.name
        if in_progress_path.exists():
            continue

        unprocessed.append(file_path)

    return unprocessed

def read_loop_status():
    """Read current iteration count from loop_status.md"""
    if not LOOP_STATUS_FILE.exists():
        return {
            'iteration': 0,
            'max_iterations': MAX_ITERATIONS,
            'started': datetime.now().isoformat(),
            'status': 'running'
        }

    try:
        content = LOOP_STATUS_FILE.read_text(encoding='utf-8')

        # Parse YAML frontmatter
        if content.startswith('---'):
            parts = content.split('---', 2)
            if len(parts) >= 3:
                frontmatter = parts[1].strip()
                status = {}
                for line in frontmatter.split('\n'):
                    if ':' in line:
                        key, value = line.split(':', 1)
                        key = key.strip()
                        value = value.strip()
                        if key == 'iteration':
                            status['iteration'] = int(value)
                        elif key == 'max_iterations':
                            status['max_iterations'] = int(value)
                        elif key == 'started':
                            status['started'] = value
                        elif key == 'status':
                            status['status'] = value
                return status
    except Exception as e:
        log(f"Error reading loop status: {e}")

    return {
        'iteration': 0,
        'max_iterations': MAX_ITERATIONS,
        'started': datetime.now().isoformat(),
        'status': 'running'
    }

def write_loop_status(status):
    """Write iteration count to loop_status.md"""
    PLANS_DIR.mkdir(parents=True, exist_ok=True)

    content = f"""---
iteration: {status['iteration']}
max_iterations: {status['max_iterations']}
started: {status['started']}
last_updated: {datetime.now().isoformat()}
status: {status['status']}
---

# Ralph Wiggum Loop Status

**Current Status**: {status['status'].upper()}

## Progress

- **Iteration**: {status['iteration']} of {status['max_iterations']}
- **Started**: {status['started']}
- **Last Updated**: {datetime.now().isoformat()}

## What This Means

This file tracks the "Ralph Wiggum Loop" - an automated system that keeps
Claude Code working on tasks until all items in `Needs_Action/` are processed
or the maximum iteration limit is reached.

### Status Values

- **running**: Loop is active, processing tasks
- **completed**: All tasks processed successfully
- **max_iterations_reached**: Stopped due to iteration limit
- **no_work**: No tasks found to process

## How It Works

1. Claude Code finishes a task and tries to exit
2. Stop hook checks for unprocessed files in `Needs_Action/`
3. If files exist and iterations < max: inject continuation prompt
4. If no files or max iterations: allow Claude to stop

## Manual Control

To stop the loop manually:
```bash
# Set status to completed
echo "status: completed" >> AI_Employee_Vault/Plans/loop_status.md

# Or delete the file
rm AI_Employee_Vault/Plans/loop_status.md
```

To reset the loop:
```bash
rm AI_Employee_Vault/Plans/loop_status.md
```

---

*Generated by Ralph Wiggum Stop Hook*
"""

    LOOP_STATUS_FILE.write_text(content, encoding='utf-8')
    log(f"Updated loop status: iteration {status['iteration']}/{status['max_iterations']}, status={status['status']}")

def main():
    """Main hook logic"""
    log("Stop hook triggered")

    # Read current status
    status = read_loop_status()
    current_iteration = status['iteration']
    max_iterations = status['max_iterations']

    log(f"Current iteration: {current_iteration}/{max_iterations}")

    # Check for unprocessed files
    unprocessed_files = get_unprocessed_files()

    log(f"Found {len(unprocessed_files)} unprocessed files")

    # Decision logic
    if len(unprocessed_files) == 0:
        # No work remaining
        log("No unprocessed files found. Allowing Claude to stop.")
        status['status'] = 'no_work'
        status['iteration'] = current_iteration
        write_loop_status(status)

        # Output completion message (to stdout for Claude to see)
        print("\n✓ TASK_COMPLETE: All items in Needs_Action/ have been processed.")
        sys.exit(0)

    elif current_iteration >= max_iterations:
        # Max iterations reached
        log(f"Max iterations ({max_iterations}) reached. Allowing Claude to stop.")
        status['status'] = 'max_iterations_reached'
        status['iteration'] = current_iteration
        write_loop_status(status)

        # Output warning message
        print(f"\n⚠ MAX_ITERATIONS_REACHED: Stopped after {max_iterations} iterations.")
        print(f"   {len(unprocessed_files)} files remain in Needs_Action/:")
        for f in unprocessed_files[:5]:  # Show first 5
            print(f"   - {f.name}")
        if len(unprocessed_files) > 5:
            print(f"   ... and {len(unprocessed_files) - 5} more")
        sys.exit(0)

    else:
        # Work remains and under max iterations - continue!
        log(f"Work remains. Injecting continuation prompt (iteration {current_iteration + 1}/{max_iterations})")

        # Increment iteration
        status['iteration'] = current_iteration + 1
        status['status'] = 'running'
        write_loop_status(status)

        # Build file list for prompt
        file_list = "\n".join([f"   - {f.name}" for f in unprocessed_files[:10]])
        if len(unprocessed_files) > 10:
            file_list += f"\n   ... and {len(unprocessed_files) - 10} more"

        # Output continuation prompt (to stdout for Claude to see)
        continuation_prompt = f"""

🔄 RALPH WIGGUM LOOP - I'M HELPING!

Continue working. There are {len(unprocessed_files)} unprocessed files in AI_Employee_Vault/Needs_Action/:

{file_list}

**Your task:**
1. Check AI_Employee_Vault/Needs_Action/ for remaining files
2. Process each file using the appropriate skill from .claude/skills/
3. Move processed files to AI_Employee_Vault/Done/
4. Create approval requests in Pending_Approval/ if needed

**Progress:** Iteration {status['iteration']} of {max_iterations}

**Note:** This is an automated continuation. The stop hook detected unfinished work and is keeping you engaged until all tasks are complete or max iterations reached.
"""

        print(continuation_prompt)
        sys.exit(0)

if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        log(f"ERROR in stop hook: {e}")
        import traceback
        traceback.print_exc(file=sys.stderr)
        # On error, allow Claude to stop
        sys.exit(0)
