"""
Daily Summary Script for Personal AI Employee

This script runs daily to:
1. Count files in key vault directories using pathlib
2. Read and update Dashboard.md with current statistics
3. Log daily metrics to JSON file

Usage: python scripts/daily_summary.py
Scheduled: Daily at 8:00 AM via Task Scheduler
"""

import json
from pathlib import Path
from datetime import datetime

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent
VAULT_PATH = PROJECT_ROOT / "AI_Employee_Vault"
DASHBOARD_PATH = PROJECT_ROOT / "Dashboard.md"
LOGS_PATH = VAULT_PATH / "Logs"

# Ensure logs directory exists
LOGS_PATH.mkdir(parents=True, exist_ok=True)


def count_files_in_directory(directory: Path) -> int:
    """Count markdown files in a directory using pathlib"""
    if not directory.exists():
        return 0
    return len(list(directory.glob("*.md")))


def get_vault_statistics() -> dict:
    """Gather statistics from all vault directories"""
    print(f"Gathering vault statistics from: {VAULT_PATH}")

    # Count files in each directory
    needs_action_count = count_files_in_directory(VAULT_PATH / "Needs_Action")
    in_progress_count = count_files_in_directory(VAULT_PATH / "Plans")  # Using Plans as In_Progress
    done_count = count_files_in_directory(VAULT_PATH / "Done")
    pending_approval_count = count_files_in_directory(VAULT_PATH / "Pending_Approval")

    print(f"  Needs_Action: {needs_action_count}")
    print(f"  In_Progress (Plans): {in_progress_count}")
    print(f"  Done: {done_count}")
    print(f"  Pending_Approval: {pending_approval_count}")

    stats = {
        "date": datetime.now().isoformat(),
        "counts": {
            "needs_action": needs_action_count,
            "in_progress": in_progress_count,
            "done": done_count,
            "pending_approval": pending_approval_count
        }
    }

    return stats


def update_dashboard(stats: dict):
    """Read Dashboard.md, update Current Status section, and save"""
    print(f"Updating Dashboard.md at: {DASHBOARD_PATH}")

    # Read current dashboard if it exists
    if DASHBOARD_PATH.exists():
        with open(DASHBOARD_PATH, 'r', encoding='utf-8') as f:
            dashboard_content = f.read()
    else:
        dashboard_content = ""

    # Get current date and time
    current_date = datetime.now().strftime("%Y-%m-%d")
    current_time = datetime.now().strftime("%H:%M:%S")

    # Create new Current Status section
    new_status_section = f"""# 📊 AI Employee Dashboard

**Last Updated:** {current_date} at {current_time}

## 📈 Current Status

| Metric | Count | Status |
|--------|-------|--------|
| **Pending Tasks** | {stats['counts']['needs_action']} | 🔴 Needs Action |
| **In Progress** | {stats['counts']['in_progress']} | 🟡 Planning |
| **Completed** | {stats['counts']['done']} | 🟢 Done |
| **Awaiting Approval** | {stats['counts']['pending_approval']} | ⏳ Pending |

## 🎯 System Health

- **Status:** 🟢 Operational
- **Last Check:** {current_time}
- **Watchers:** Active
- **Orchestrator:** Running

## 📝 Quick Actions

- Process pending tasks: `claude skill process-tasks`
- Update dashboard: `claude skill update-dashboard`
- Generate reports: `claude skill generate-reports`

---
*Auto-generated by Daily Summary Script*
*Next update: Tomorrow at 8:00 AM*
"""

    # Write updated dashboard
    with open(DASHBOARD_PATH, 'w', encoding='utf-8') as f:
        f.write(new_status_section)

    print("[OK] Dashboard.md updated successfully")


def save_daily_log(stats: dict):
    """Save daily statistics to JSON log file"""
    # Create filename with YYYYMMDD format
    date_str = datetime.now().strftime("%Y%m%d")
    log_filename = f"daily_{date_str}.json"
    log_path = LOGS_PATH / log_filename

    print(f"Saving daily log to: {log_path}")

    # Save log with exact format specified
    with open(log_path, 'w', encoding='utf-8') as f:
        json.dump(stats, f, indent=2, ensure_ascii=False)

    print(f"[OK] Daily log saved: {log_filename}")


def main():
    """Main execution function"""
    print("=" * 70)
    print("AI Employee - Daily Summary")
    print("=" * 70)
    print(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print()

    try:
        # Step 1: Count files in vault directories
        stats = get_vault_statistics()
        print()

        # Step 2 & 3: Read and update Dashboard.md
        update_dashboard(stats)
        print()

        # Step 4: Save JSON log
        save_daily_log(stats)
        print()

        print("=" * 70)
        print("[SUCCESS] Daily Summary Complete!")
        print("=" * 70)
        print()
        print(f"Summary:")
        print(f"  - Needs Action: {stats['counts']['needs_action']}")
        print(f"  - In Progress: {stats['counts']['in_progress']}")
        print(f"  - Done: {stats['counts']['done']}")
        print(f"  - Pending Approval: {stats['counts']['pending_approval']}")
        print()

    except Exception as e:
        print()
        print(f"[ERROR] {e}")
        import traceback
        traceback.print_exc()
        exit(1)


if __name__ == "__main__":
    main()
